config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  root 'home#index'
  
  get '/about' => 'home#about'

  post '/questions' => 'home#temp'

  post '/answers' => 'home#temp'

  get '/question/:id' => 'questions#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord

    belongs_to :question

    def gravatar
        "http://gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}"
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord

    has_many :answers

    def gravatar
        "http://gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}"
    end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

    def create
        question = Question.find(params[:answer][:question_id])
        question.answers.create(answer_params)
        redirect_to question
    end

    private

    def answer_params
        params.require(:answer).permit(:question_id, :email, :body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @questions = Question.order(created_at: :desc).all
  end

  def about
  end

  def temp
    redirect_to root_path
  end  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

    def show
        @question = Question.find(params[:id])
    end

    def create
        Question.create(question_params)

        redirect_to root_path
    end

    private

    def question_params
        params.require(:question).permit(:email, :body)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="/">History of the Universe</a>
    <form class="form-inline">
        <button
        class="btn btn-success"
        type="button"
        data-toggle="modal"
        data-target="#modalAsk"
        >
        Ask Question
        </button>
    </form>
</nav>

app/views/home/_new_answer_form.html.erb
<div id="modalAnswer" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">New Answer</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <%= form_for :answer, url: '/answers' do %>
            <input type="hidden" name="answer[question_id]" value="<%= @question.id%>"/>
        <div class="modal-body">    
            <div class="form-group row">
                <label class="col-sm-4" for="inputEmail">Email address</label>
                <input type="email" class="form-control col-sm-8" id="inputEmail" name="answer[email]" aria-describedby="emailHelp" placeholder="Enter email" required>
            </div>
            <div class="form-group row">
                <label class="col-sm-4" for="textareaQuestion">Question</label>
                <textarea class="form-control col-sm-8" id="textareaQuestion" name="answer[body]" placeholder="What is your answer?" required></textarea>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
        <% end %>
    </div>
    </div>
</div>

app/views/home/_new_question_form.html.erb
<div id="modalAsk" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">New Question</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <%= form_for :question, url: '/questions' do %>
        <div class="modal-body">    
            <div class="form-group row">
                <label class="col-sm-4" for="inputEmail">Email address</label>
                <input type="email" class="form-control col-sm-8" id="inputEmail" name="question[email]" aria-describedby="emailHelp" placeholder="Enter email" required>
            </div>
            <div class="form-group row">
                <label class="col-sm-4" for="textareaQuestion">Question</label>
                <textarea class="form-control col-sm-8" id="textareaQuestion" name="question[body]" placeholder="Are there such things as aliens?" required></textarea>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
        <% end %>
    </div>
    </div>
</div>

app/views/home/about.html.erb
<h1>About</h1>
<p>Lipsum</p>

app/views/home/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-5">The universe is the totality of everything that exists, has existed, or ever will exist.</h1>
    <p>This Q&A site is dedicated to questions about the history of the universe.</p>
  </div>
</div>

<% 
  @questions.each do |q| 
  # https://via.placeholder.com/100
%>
  
<div class="media mt-4">
  <img src="<%= q.gravatar %>" class="mr-3">
  <div class="media-body">
    <h5 class="mt-0"><%= q.email %> asked:</h5>
    <span><%= time_ago_in_words q.created_at %> ago</span>
    <p><%= q.body %></p>
    <div class="d-flex flex-row-reverse">
      <a class="btn btn-info" href="<%= question_path(q) %>" role="button">View Answers</a>
    </div>
    <hr/>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>History of the Universe :: Rails Example</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col">

          <!-- navbar/header -->
          <%= render 'home/navbar' %>

          <!-- content -->
          <%= yield %>
        </div>
      </div>
    </div>

    <!-- modal -->
    <%= render 'home/new_question_form' %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/questions/show.html.erb
<div class="jumbotron">
    <div class="media mt-3">
        <img src="<%= @question.gravatar %>" class="mr-3">
        <div class="media-body">
            <h5 class="mt-0 display-4"><%= @question.email %> asked:</h5>
            <p class="lead"><%= @question.body %></p>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-10 offset-md-2">

            <button 
                class="btn btn-primary"
                data-toggle="modal"
                data-target="#modalAnswer"
            >
                Submit new answer
            </button>

            <%= render 'home/new_answer_form' %>
            
            <% @question.answers.each do |answer| %>
            <div class="media mt-3">
                <img src="<%= @answer.gravatar %>" class="mr-3">
                <div class="media-body">
                    <h5 class="mt-0"><%= @answer.email %> asked:</h5>
                    <p><%= @answer.body%></p>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>